"""
GitHub service for PHRAXIS.
Creates pull requests with generated code changes.
"""
import logging
from typing import Dict, Any, List, Optional
from datetime import datetime
import base64

from github import Github, GithubException
from github.Repository import Repository
from github.GitRef import GitRef

from backend.env_loader import get_config

logger = logging.getLogger(__name__)


class GitHubServiceError(Exception):
    """Raised when GitHub service encounters an error."""
    pass


class GitHubService:
    """
    GitHub API service wrapper.
    Handles branch creation, file commits, and pull request creation.
    """
    
    def __init__(self):
        """Initialize the GitHub service with credentials."""
        config = get_config()
        
        try:
            self.github = Github(config.GITHUB_TOKEN)
            self.repo_owner = config.GITHUB_REPO_OWNER
            self.repo_name = config.GITHUB_REPO_NAME
            
            # Get repository object
            repo_full_name = f"{self.repo_owner}/{self.repo_name}"
            self.repo: Repository = self.github.get_repo(repo_full_name)
            
            logger.info(f"GitHub service initialized for repository: {repo_full_name}")
        except GithubException as e:
            logger.error(f"Failed to initialize GitHub service: {e}")
            raise GitHubServiceError(f"GitHub initialization failed: {e}")
        except Exception as e:
            logger.error(f"Unexpected error initializing GitHub service: {e}")
            raise GitHubServiceError(f"GitHub initialization failed: {e}")
    
    def create_pr(
        self,
        repo_owner: str,
        repo_name: str,
        branch_name: str,
        files_changed: Dict[str, str],
        intent: Dict[str, Any],
        transcript: str
    ) -> Dict[str, Any]:
        """
        Create a pull request with generated code changes.
        
        Args:
            repo_owner: Repository owner (can override config)
            repo_name: Repository name (can override config)
            branch_name: Name for the new branch
            files_changed: Dictionary mapping file paths to their new content
            intent: Structured intent that generated the code
            transcript: Original voice transcript
        
        Returns:
            Dictionary containing:
                - pr_url (str): URL of the created pull request
                - pr_number (int): Pull request number
                - branch_name (str): Name of the created branch
                - files_committed (list): List of files committed
                - commit_sha (str): SHA of the commit
        
        Raises:
            GitHubServiceError: If PR creation fails
        """
        try:
            # Use provided repo or fall back to configured repo
            if repo_owner != self.repo_owner or repo_name != self.repo_name:
                repo_full_name = f"{repo_owner}/{repo_name}"
                repo = self.github.get_repo(repo_full_name)
                logger.info(f"Using repository: {repo_full_name}")
            else:
                repo = self.repo
            
            logger.info(f"Creating PR for {len(files_changed)} files on branch: {branch_name}")
            
            # Step 1: Create new branch from main
            base_branch = "main"
            new_branch_ref = self._create_branch(repo, branch_name, base_branch)
            
            # Step 2: Commit all files to the new branch
            commit_sha = self._commit_files(repo, branch_name, files_changed, intent)
            
            # Step 3: Create pull request
            pr_title = f"feat: {intent.get('action', 'code generation')} — generated by PHRAXIS"
            pr_body = self._generate_pr_body(intent, transcript, files_changed)
            
            pull_request = repo.create_pull(
                title=pr_title,
                body=pr_body,
                head=branch_name,
                base=base_branch
            )
            
            logger.info(f"Pull request created: #{pull_request.number} - {pull_request.html_url}")
            
            return {
                "pr_url": pull_request.html_url,
                "pr_number": pull_request.number,
                "branch_name": branch_name,
                "files_committed": list(files_changed.keys()),
                "commit_sha": commit_sha,
                "status": "success"
            }
            
        except GithubException as e:
            error_msg = f"GitHub API error while creating PR: {e.status} - {e.data}"
            logger.error(error_msg)
            raise GitHubServiceError(error_msg)
        
        except Exception as e:
            error_msg = f"Unexpected error while creating PR: {str(e)}"
            logger.error(error_msg)
            raise GitHubServiceError(error_msg)
    
    def _create_branch(
        self,
        repo: Repository,
        branch_name: str,
        base_branch: str = "main"
    ) -> GitRef:
        """
        Create a new branch from base branch.
        
        Args:
            repo: Repository object
            branch_name: Name for the new branch
            base_branch: Base branch to branch from
        
        Returns:
            GitRef object for the new branch
        
        Raises:
            GitHubServiceError: If branch creation fails
        """
        try:
            # Get the base branch reference
            base_ref = repo.get_git_ref(f"heads/{base_branch}")
            base_sha = base_ref.object.sha
            
            logger.info(f"Creating branch '{branch_name}' from '{base_branch}' (SHA: {base_sha[:7]})")
            
            # Check if branch already exists
            try:
                existing_ref = repo.get_git_ref(f"heads/{branch_name}")
                logger.warning(f"Branch '{branch_name}' already exists, deleting it")
                existing_ref.delete()
            except GithubException as e:
                if e.status != 404:
                    raise
            
            # Create new branch
            new_ref = repo.create_git_ref(
                ref=f"refs/heads/{branch_name}",
                sha=base_sha
            )
            
            logger.info(f"Branch created successfully: {branch_name}")
            return new_ref
            
        except GithubException as e:
            error_msg = f"Failed to create branch '{branch_name}': {e.status} - {e.data}"
            logger.error(error_msg)
            raise GitHubServiceError(error_msg)
    
    def _commit_files(
        self,
        repo: Repository,
        branch_name: str,
        files_changed: Dict[str, str],
        intent: Dict[str, Any]
    ) -> str:
        """
        Commit multiple files to a branch.
        
        Args:
            repo: Repository object
            branch_name: Branch to commit to
            files_changed: Dictionary of file paths to content
            intent: Intent that generated the changes
        
        Returns:
            SHA of the commit
        
        Raises:
            GitHubServiceError: If commit fails
        """
        try:
            # Get the branch reference
            branch_ref = repo.get_git_ref(f"heads/{branch_name}")
            base_tree_sha = repo.get_git_commit(branch_ref.object.sha).tree.sha
            
            logger.info(f"Committing {len(files_changed)} files to branch: {branch_name}")
            
            # Create tree elements for all files
            tree_elements = []
            for file_path, content in files_changed.items():
                logger.debug(f"Preparing file: {file_path} ({len(content)} bytes)")
                
                # Create blob for file content
                blob = repo.create_git_blob(content, "utf-8")
                
                tree_elements.append({
                    "path": file_path,
                    "mode": "100644",  # Regular file
                    "type": "blob",
                    "sha": blob.sha
                })
            
            # Create tree
            tree = repo.create_git_tree(tree_elements, base_tree_sha)
            
            # Create commit
            commit_message = self._generate_commit_message(intent, files_changed)
            parent_commit = repo.get_git_commit(branch_ref.object.sha)
            
            commit = repo.create_git_commit(
                message=commit_message,
                tree=tree,
                parents=[parent_commit]
            )
            
            # Update branch reference to point to new commit
            branch_ref.edit(commit.sha)
            
            logger.info(f"Files committed successfully: {commit.sha[:7]}")
            return commit.sha
            
        except GithubException as e:
            error_msg = f"Failed to commit files: {e.status} - {e.data}"
            logger.error(error_msg)
            raise GitHubServiceError(error_msg)
    
    def _generate_commit_message(
        self,
        intent: Dict[str, Any],
        files_changed: Dict[str, str]
    ) -> str:
        """
        Generate a descriptive commit message.
        
        Args:
            intent: Intent that generated the changes
            files_changed: Files that were changed
        
        Returns:
            Commit message string
        """
        action = intent.get('action', 'code generation')
        parameters = intent.get('parameters', {})
        
        # Build commit message
        message_lines = [
            f"feat: {action}",
            "",
            "Generated by PHRAXIS voice-to-code system",
            "",
            "Changes:",
        ]
        
        # Add file list
        for file_path in sorted(files_changed.keys()):
            message_lines.append(f"  - {file_path}")
        
        # Add parameters if present
        if parameters:
            message_lines.append("")
            message_lines.append("Parameters:")
            for key, value in parameters.items():
                message_lines.append(f"  - {key}: {value}")
        
        return "\n".join(message_lines)
    
    def _generate_pr_body(
        self,
        intent: Dict[str, Any],
        transcript: str,
        files_changed: Dict[str, str]
    ) -> str:
        """
        Generate pull request body with detailed information.
        
        Args:
            intent: Structured intent
            transcript: Original voice transcript
            files_changed: Files that were changed
        
        Returns:
            PR body markdown string
        """
        action = intent.get('action', 'unknown')
        parameters = intent.get('parameters', {})
        constraints = intent.get('constraints', [])
        confidence = intent.get('confidence', 0.0)
        bob_session_id = intent.get('bob_session_id', 'N/A')
        
        # Build PR body
        body_lines = [
            "## 🎤 PHRAXIS Generated Code",
            "",
            "This pull request was automatically generated by PHRAXIS, an AI-powered voice-to-code system.",
            "",
            "### 📝 Original Voice Command",
            f"> {transcript}",
            "",
            "### 🎯 Extracted Intent",
            f"- **Action**: `{action}`",
            f"- **Confidence**: {confidence:.2%}",
        ]
        
        # Add parameters
        if parameters:
            body_lines.append("")
            body_lines.append("### ⚙️ Parameters")
            for key, value in parameters.items():
                body_lines.append(f"- **{key}**: `{value}`")
        
        # Add constraints
        if constraints:
            body_lines.append("")
            body_lines.append("### 📋 Constraints")
            for constraint in constraints:
                body_lines.append(f"- {constraint}")
        
        # Add files changed
        body_lines.extend([
            "",
            "### 📁 Files Changed",
            f"This PR modifies {len(files_changed)} file(s):",
            ""
        ])
        
        for file_path in sorted(files_changed.keys()):
            lines = files_changed[file_path].count('\n') + 1
            body_lines.append(f"- `{file_path}` ({lines} lines)")
        
        # Add Bob session reference
        body_lines.extend([
            "",
            "### 🤖 Bob Session",
            f"Session ID: `{bob_session_id}`",
            "",
            "---",
            "",
            "**Generated by**: IBM Bob + IBM Watson STT + IBM Watson NLU",
            f"**Timestamp**: {datetime.utcnow().isoformat()}Z",
        ])
        
        return "\n".join(body_lines)
    
    def get_pr(self, pr_number: int) -> Dict[str, Any]:
        """
        Get pull request details.
        
        Args:
            pr_number: Pull request number
        
        Returns:
            Dictionary with PR details
        
        Raises:
            GitHubServiceError: If PR retrieval fails
        """
        try:
            pr = self.repo.get_pull(pr_number)
            
            return {
                "number": pr.number,
                "title": pr.title,
                "body": pr.body,
                "state": pr.state,
                "url": pr.html_url,
                "created_at": pr.created_at.isoformat(),
                "updated_at": pr.updated_at.isoformat(),
                "merged": pr.merged,
                "mergeable": pr.mergeable,
                "head_branch": pr.head.ref,
                "base_branch": pr.base.ref
            }
            
        except GithubException as e:
            error_msg = f"Failed to get PR #{pr_number}: {e.status} - {e.data}"
            logger.error(error_msg)
            raise GitHubServiceError(error_msg)
    
    def list_prs(self, state: str = "open", limit: int = 20) -> List[Dict[str, Any]]:
        """
        List pull requests.
        
        Args:
            state: PR state ("open", "closed", "all")
            limit: Maximum number of PRs to return
        
        Returns:
            List of PR dictionaries
        
        Raises:
            GitHubServiceError: If listing fails
        """
        try:
            prs = self.repo.get_pulls(state=state)
            
            result = []
            for pr in prs[:limit]:
                result.append({
                    "number": pr.number,
                    "title": pr.title,
                    "state": pr.state,
                    "url": pr.html_url,
                    "created_at": pr.created_at.isoformat(),
                    "head_branch": pr.head.ref,
                    "base_branch": pr.base.ref
                })
            
            logger.info(f"Retrieved {len(result)} PRs with state: {state}")
            return result
            
        except GithubException as e:
            error_msg = f"Failed to list PRs: {e.status} - {e.data}"
            logger.error(error_msg)
            raise GitHubServiceError(error_msg)
    
    def health_check(self) -> bool:
        """
        Check if the GitHub service is accessible and working.
        
        Returns:
            True if service is healthy, False otherwise
        """
        try:
            # Try to get repository info as health check
            self.repo.get_branches()
            logger.info("GitHub service health check passed")
            return True
        except Exception as e:
            logger.error(f"GitHub service health check failed: {e}")
            return False


# Made with Bob